# This file describes a conda environment that can be to install the JWST
#   validation notebooks
#
# Run the following command to set up this environment:
# $ conda env create -f environment.yml
#
# The environment name can be overridden with the following command:
# $ conda env create -n <custom name> -f environment.yml
#
# Run the following command to activate the environment:
# $ conda activate abscal
#
# To deactivate the environment run the following command:
# $ conda deactivate
#
# To remove the environment entirely, run the following command:
# $ conda remove -n abscal --all

name: abscal

channels:
  - conda-forge
  - astropy
  - http://ssb.stsci.edu/astroconda
  - defaults

dependencies:
  # Base dependencies
  - pip
  - python>=3.9 # because abscal uses dictionary merging.
  - Cython
  - jupyter
  - nb_conda

  - pip:
    # Major modules
    - numpy
    - astropy
    - matplotlib
    - scipy
    - jupyter
    - photutils
    - ipykernel
    - rebin
    - tox
    - sphinx
    - sphinx_rtd_theme
    - stsci_rtd_theme
    - sphinx_autoapi
    - pyyaml

#variables:
#  WFC3_REF: "NEEDS TO BE A RELATIVE PATH"

