PRO RMS,DATA,FRST,LAST
; 91DEC7-QUICK PROG TO COMPUTE AVG SPECTRUM AND RMS DEV FROM AVG
;
NPTS=LAST-FRST+1
AVG=TOTAL(DATA(FRST:LAST))/NPTS
RMS=SQRT(TOTAL((DATA(FRST:LAST)-AVG)^2)/NPTS)
FRAC=RMS/AVG
PRINT,'AVG,RMS, AND FRAC RMS=',AVG,RMS,FRAC
RETURN                                                            
END                                
