#! /usr/bin/env python
"""
This file acts as an IDL interface (using the IDL `prewfc` name) to the wfc3_coadd 
command.

Author
-------
- Brian York

Use
---
This file is intended to be run from the command line::

    prewfc [options] table
"""

from wfc3_coadd import main as extract_function

def main(**kwargs):

    kwargs['compat'] = True

    extract_function(**kwargs)


if __name__ == "__main__":
    main()
