#! /usr/bin/env python
"""
This file acts as an IDL interface (using the IDL `prewfc` name) to the wfc3_extract 
command.

Author
-------
- Brian York

Use
---
This file is intended to be run from the command line::

    prewfc [options] table
"""

from wfc3_extract import main as extract_function

def main(overrides={}):

    overrides['compat'] = True

    extract_function(overrides=overrides)


if __name__ == "__main__":
    main()
