#! /usr/bin/env python
"""
This module acts as an interface to the WFC3 'reduce_grism_coadd' script.

Author
-------
- Brian York

Use
---
This module is intended to be run from the command line::

    wfc3_coadd [options] input_table
"""

from abscal.wfc3.reduce_grism_coadd import main as do_coadd


def main(**kwargs):

    do_coadd(**kwargs)


if __name__ == "__main__":
    main()
