#! /usr/bin/env python
"""
This module acts as an interface to the WFC3 'preprocess_table_create' script.

Author
-------
- Brian York

Use
---
This module is intended to be run from the command line::

    wfc3_setup [options] 'input search pattern'
"""

from abscal.wfc3.preprocess_table_create import main as do_create


def main(**kwargs):

    do_create(**kwargs)


if __name__ == "__main__":
    main()
