#! /usr/bin/env python
"""
This module acts as an interface to the 'wlmeas' part of the WFC3 
`reduce_grism_wavelength` script. 

Author
-------
- Brian York

Use
---
This module is intended to be run from the command line::

    wfc3_wave_find_lines [options] <input table>
"""

from abscal.wfc3.reduce_grism_wavelength import main as do_wl_process


def main(overrides={}):

    do_wl_process(overrides=overrides, do_measure=True, do_make=False)


if __name__ == "__main__":
    main()
