#! /usr/bin/env python
"""
This file acts as an IDL interface (using the IDL `wfcdir` name) to the wfc3_setup 
command.

Author
-------
- Brian York

Use
---
This file is intended to be run from the command line::

    wfcdir [options] table
"""

from wfc3_setup import main as do_create


def main(**kwargs):

    kwargs['compat'] = True

    do_create(**kwargs)


if __name__ == "__main__":
    main()
