#! /usr/bin/env python
"""
This file acts as an IDL interface (using the IDL `wlmake` name) to the `wfc3_wave_solve`
command.

Author
-------
- Brian York

Use
---
This file is intended to be run from the command line::

    wlmake [options] table
"""

from wfc3_wave_solve import main as do_wl_process


def main(overrides={}):

    overrides['compat'] = True

    do_wl_process(overrides=overrides, do_measure=False, do_make=True)


if __name__ == "__main__":
    main()
